language: python
python: 
  - "2.6"
  - "2.7"
  - "3.5"
  - "3.3"
  - "3.4"

install: 
  - pip install coverage
  - pip install codecov
  - pip install releases
  
script: coverage run --source=algopy setup.py test

after_success: 
  - codecov
